# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import expenses_usermanagement_pb2 as expenses__usermanagement__pb2


class UserManagementStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddUser = channel.unary_unary(
        '/user_management.UserManagement/AddUser',
        request_serializer=expenses__usermanagement__pb2.AddUserReply.SerializeToString,
        response_deserializer=expenses__usermanagement__pb2.AddUserReply.FromString,
        )


class UserManagementServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserManagementServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddUser': grpc.unary_unary_rpc_method_handler(
          servicer.AddUser,
          request_deserializer=expenses__usermanagement__pb2.AddUserReply.FromString,
          response_serializer=expenses__usermanagement__pb2.AddUserReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user_management.UserManagement', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
