# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: expenses_usermanagement.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='expenses_usermanagement.proto',
  package='user_management',
  syntax='proto3',
  serialized_options=b'\252\002\037AcademyCloud.Resources.Services',
  serialized_pb=b'\n\x1d\x65xpenses_usermanagement.proto\x12\x0fuser_management\"\x10\n\x0e\x41\x64\x64UserRequest\"\x0e\n\x0c\x41\x64\x64UserReply2Y\n\x0eUserManagement\x12G\n\x07\x41\x64\x64User\x12\x1d.user_management.AddUserReply\x1a\x1d.user_management.AddUserReplyB\"\xaa\x02\x1f\x41\x63\x61\x64\x65myCloud.Resources.Servicesb\x06proto3'
)




_ADDUSERREQUEST = _descriptor.Descriptor(
  name='AddUserRequest',
  full_name='user_management.AddUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=66,
)


_ADDUSERREPLY = _descriptor.Descriptor(
  name='AddUserReply',
  full_name='user_management.AddUserReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['AddUserRequest'] = _ADDUSERREQUEST
DESCRIPTOR.message_types_by_name['AddUserReply'] = _ADDUSERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddUserRequest = _reflection.GeneratedProtocolMessageType('AddUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERREQUEST,
  '__module__' : 'expenses_usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:user_management.AddUserRequest)
  })
_sym_db.RegisterMessage(AddUserRequest)

AddUserReply = _reflection.GeneratedProtocolMessageType('AddUserReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERREPLY,
  '__module__' : 'expenses_usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:user_management.AddUserReply)
  })
_sym_db.RegisterMessage(AddUserReply)


DESCRIPTOR._options = None

_USERMANAGEMENT = _descriptor.ServiceDescriptor(
  name='UserManagement',
  full_name='user_management.UserManagement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=84,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='user_management.UserManagement.AddUser',
    index=0,
    containing_service=None,
    input_type=_ADDUSERREPLY,
    output_type=_ADDUSERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERMANAGEMENT)

DESCRIPTOR.services_by_name['UserManagement'] = _USERMANAGEMENT

# @@protoc_insertion_point(module_scope)
