version: '3.4'

services:
  consul:
    image: consul:latest
    ports: 
      - "8500:8500"
      - "8300:8300"
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
  registrator:
    image: gliderlabs/registrator:master
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    depends_on:
      - registrator
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  identity.service:
    image: ${DOCKER_REGISTRY-}identityservice
    depends_on:
      - registrator
      - db
    build:
      context: .
      dockerfile: Identity/Identity.Service/Dockerfile
  expenses.service:
    image: ${DOCKER_REGISTRY-}expensesservice
    depends_on:
      - registrator
      - db
    build:
      context: .
      dockerfile: Expenses/Expenses.Service/Dockerfile
  resources.service:
    image: ${DOCKER_REGISTRY-}resourcesservice
    depends_on:
      - registrator
      - db
    build:
      context: ./Resources/Resources
      dockerfile: Dockerfile
  api:
    image: ${DOCKER_REGISTRY-}api
    depends_on:
      - identity.service
      - expenses.service
      - resources.service
    build:
      context: .
      dockerfile: API/Dockerfile
