version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

  identity.service:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Identity/Identity.Service/Dockerfile

