# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7"
  config.vm.synced_folder ".", "/vagrant", type: 'virtualbox'

  # Enable bridged public network as provided network
  # Disable auto config of public_network
  config.vm.network "public_network", 
    bridge: "Realtek USB GbE Family Controller",
    auto_config: false

  # Login as root
  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  # Disable VBGuest auto update
  config.vbguest.auto_update = false

  # Enable auto host management
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.manage_host = false

  # Common config for virtualbox
  def vb_common_config(vb)
    vb.linked_clone = true
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']

    # Enable promiscuous mode for bridged network
    # https://ask.openstack.org/en/question/120950/cannot-ping-router-on-provider-network-from-controller-node/
    vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
  end

  # Provisions
  config.vm.provision "shell", path: "scripts/init.sh"

  config.vm.define "controller", primary: true do |controller|
    controller.vm.hostname =  "controller"
    controller.vm.network "private_network", ip: "192.168.56.2"

    # open another public_network with ip 10.0.0.77 
    # to allow access from other machines in the same local network
    controller.vm.network "public_network", ip: "10.0.0.77"
    controller.vm.provider "virtualbox" do |vb|
      vb.name = "openstack_controller"
      vb.cpus = 4
      vb.memory = 4096
      vb_common_config(vb)
    end
  end

  config.vm.define "compute1" do |compute1|
    compute1.vm.hostname = "compute1"
    compute1.vm.network "private_network", ip: "192.168.56.3"
    compute1.vm.provider "virtualbox" do |vb|
      vb.name = "openstack_compute1"
      vb.cpus = 2
      vb.memory = 2048
      vb_common_config(vb)
    end
  end

  config.vm.define "block-storage" do |bs|
    bs.vm.hostname = "block-storage"
    bs.vm.network "private_network", ip: "192.168.56.4"
    bs.vm.provider "virtualbox" do |vb|
      vb.name = "openstack_block-storage"
      vb.cpus = 1
      vb.memory = 1024
      vb_common_config(vb)

      # Create and mount storage disk
      line = `vboxmanage list systemproperties`.split(/\n/).grep(/Default machine folder/).first
      vb_machine_folder = line.split(':').drop(1).join(':').strip()
      storage_disk_path = File.join(vb_machine_folder, vb.name, 'disk2.vdi')
      unless File.exist?(storage_disk_path)
        vb.customize ['createhd', '--filename', storage_disk_path, '--format', 'VDI', '--size', 60 * 1024]
      end
      vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--portcount', '2']
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storage_disk_path]
    end
 end
end
