# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity.proto',
  package='identity',
  syntax='proto3',
  serialized_options=b'\252\002/AcademyCloud.ResourceManagement.Protos.Identity',
  serialized_pb=b'\n\x0eidentity.proto\x12\x08identity\"T\n\x0e\x41\x64\x64UserRequest\x12\x1f\n\x17userProjectAssignmentId\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x11\n\tprojectId\x18\x03 \x01(\t\"\x11\n\x0f\x41\x64\x64UserResponse\"#\n\x11\x44\x65leteUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteUserResponse\"A\n\x1cRemoveUserFromProjectRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x11\n\tprojectId\x18\x02 \x01(\t\"\x1f\n\x1dRemoveUserFromProjectResponse\")\n\x14\x44\x65leteProjectRequest\x12\x11\n\tprojectId\x18\x01 \x01(\t\"\x17\n\x15\x44\x65leteProjectResponse2\xcf\x02\n\x08Identity\x12>\n\x07\x41\x64\x64User\x12\x18.identity.AddUserRequest\x1a\x19.identity.AddUserResponse\x12h\n\x15RemoveUserFromProject\x12&.identity.RemoveUserFromProjectRequest\x1a\'.identity.RemoveUserFromProjectResponse\x12P\n\rDeleteProject\x12\x1e.identity.DeleteProjectRequest\x1a\x1f.identity.DeleteProjectResponse\x12G\n\nDeleteUser\x12\x1b.identity.DeleteUserRequest\x1a\x1c.identity.DeleteUserResponseB2\xaa\x02/AcademyCloud.ResourceManagement.Protos.Identityb\x06proto3'
)




_ADDUSERREQUEST = _descriptor.Descriptor(
  name='AddUserRequest',
  full_name='identity.AddUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userProjectAssignmentId', full_name='identity.AddUserRequest.userProjectAssignmentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='identity.AddUserRequest.userId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projectId', full_name='identity.AddUserRequest.projectId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=112,
)


_ADDUSERRESPONSE = _descriptor.Descriptor(
  name='AddUserResponse',
  full_name='identity.AddUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=131,
)


_DELETEUSERREQUEST = _descriptor.Descriptor(
  name='DeleteUserRequest',
  full_name='identity.DeleteUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='identity.DeleteUserRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=168,
)


_DELETEUSERRESPONSE = _descriptor.Descriptor(
  name='DeleteUserResponse',
  full_name='identity.DeleteUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=190,
)


_REMOVEUSERFROMPROJECTREQUEST = _descriptor.Descriptor(
  name='RemoveUserFromProjectRequest',
  full_name='identity.RemoveUserFromProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='identity.RemoveUserFromProjectRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projectId', full_name='identity.RemoveUserFromProjectRequest.projectId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=257,
)


_REMOVEUSERFROMPROJECTRESPONSE = _descriptor.Descriptor(
  name='RemoveUserFromProjectResponse',
  full_name='identity.RemoveUserFromProjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=290,
)


_DELETEPROJECTREQUEST = _descriptor.Descriptor(
  name='DeleteProjectRequest',
  full_name='identity.DeleteProjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectId', full_name='identity.DeleteProjectRequest.projectId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=333,
)


_DELETEPROJECTRESPONSE = _descriptor.Descriptor(
  name='DeleteProjectResponse',
  full_name='identity.DeleteProjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=358,
)

DESCRIPTOR.message_types_by_name['AddUserRequest'] = _ADDUSERREQUEST
DESCRIPTOR.message_types_by_name['AddUserResponse'] = _ADDUSERRESPONSE
DESCRIPTOR.message_types_by_name['DeleteUserRequest'] = _DELETEUSERREQUEST
DESCRIPTOR.message_types_by_name['DeleteUserResponse'] = _DELETEUSERRESPONSE
DESCRIPTOR.message_types_by_name['RemoveUserFromProjectRequest'] = _REMOVEUSERFROMPROJECTREQUEST
DESCRIPTOR.message_types_by_name['RemoveUserFromProjectResponse'] = _REMOVEUSERFROMPROJECTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteProjectRequest'] = _DELETEPROJECTREQUEST
DESCRIPTOR.message_types_by_name['DeleteProjectResponse'] = _DELETEPROJECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddUserRequest = _reflection.GeneratedProtocolMessageType('AddUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.AddUserRequest)
  })
_sym_db.RegisterMessage(AddUserRequest)

AddUserResponse = _reflection.GeneratedProtocolMessageType('AddUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERRESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.AddUserResponse)
  })
_sym_db.RegisterMessage(AddUserResponse)

DeleteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.DeleteUserRequest)
  })
_sym_db.RegisterMessage(DeleteUserRequest)

DeleteUserResponse = _reflection.GeneratedProtocolMessageType('DeleteUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERRESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.DeleteUserResponse)
  })
_sym_db.RegisterMessage(DeleteUserResponse)

RemoveUserFromProjectRequest = _reflection.GeneratedProtocolMessageType('RemoveUserFromProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEUSERFROMPROJECTREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.RemoveUserFromProjectRequest)
  })
_sym_db.RegisterMessage(RemoveUserFromProjectRequest)

RemoveUserFromProjectResponse = _reflection.GeneratedProtocolMessageType('RemoveUserFromProjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEUSERFROMPROJECTRESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.RemoveUserFromProjectResponse)
  })
_sym_db.RegisterMessage(RemoveUserFromProjectResponse)

DeleteProjectRequest = _reflection.GeneratedProtocolMessageType('DeleteProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPROJECTREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.DeleteProjectRequest)
  })
_sym_db.RegisterMessage(DeleteProjectRequest)

DeleteProjectResponse = _reflection.GeneratedProtocolMessageType('DeleteProjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPROJECTRESPONSE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:identity.DeleteProjectResponse)
  })
_sym_db.RegisterMessage(DeleteProjectResponse)


DESCRIPTOR._options = None

_IDENTITY = _descriptor.ServiceDescriptor(
  name='Identity',
  full_name='identity.Identity',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=361,
  serialized_end=696,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='identity.Identity.AddUser',
    index=0,
    containing_service=None,
    input_type=_ADDUSERREQUEST,
    output_type=_ADDUSERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveUserFromProject',
    full_name='identity.Identity.RemoveUserFromProject',
    index=1,
    containing_service=None,
    input_type=_REMOVEUSERFROMPROJECTREQUEST,
    output_type=_REMOVEUSERFROMPROJECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteProject',
    full_name='identity.Identity.DeleteProject',
    index=2,
    containing_service=None,
    input_type=_DELETEPROJECTREQUEST,
    output_type=_DELETEPROJECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteUser',
    full_name='identity.Identity.DeleteUser',
    index=3,
    containing_service=None,
    input_type=_DELETEUSERREQUEST,
    output_type=_DELETEUSERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IDENTITY)

DESCRIPTOR.services_by_name['Identity'] = _IDENTITY

# @@protoc_insertion_point(module_scope)
