# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import instance_pb2 as instance__pb2


class InstanceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetInstances = channel.unary_unary(
        '/instance.InstanceService/GetInstances',
        request_serializer=instance__pb2.GetInstancesRequest.SerializeToString,
        response_deserializer=instance__pb2.GetInstancesResponse.FromString,
        )
    self.GetFlavors = channel.unary_unary(
        '/instance.InstanceService/GetFlavors',
        request_serializer=instance__pb2.GetFlavorsRequest.SerializeToString,
        response_deserializer=instance__pb2.GetFlavorsResponse.FromString,
        )
    self.GetImages = channel.unary_unary(
        '/instance.InstanceService/GetImages',
        request_serializer=instance__pb2.GetImagesRequest.SerializeToString,
        response_deserializer=instance__pb2.GetImagesResponse.FromString,
        )
    self.CreateInstance = channel.unary_unary(
        '/instance.InstanceService/CreateInstance',
        request_serializer=instance__pb2.CreateInstanceRequest.SerializeToString,
        response_deserializer=instance__pb2.CreateInstanceResponse.FromString,
        )
    self.StartInstance = channel.unary_unary(
        '/instance.InstanceService/StartInstance',
        request_serializer=instance__pb2.StartInstanceRequest.SerializeToString,
        response_deserializer=instance__pb2.StartInstanceResponse.FromString,
        )
    self.StopInstance = channel.unary_unary(
        '/instance.InstanceService/StopInstance',
        request_serializer=instance__pb2.StopInstanceRequest.SerializeToString,
        response_deserializer=instance__pb2.StopInstanceResponse.FromString,
        )
    self.DeleteInstance = channel.unary_unary(
        '/instance.InstanceService/DeleteInstance',
        request_serializer=instance__pb2.DeleteInstanceRequest.SerializeToString,
        response_deserializer=instance__pb2.DeleteInstanceResponse.FromString,
        )
    self.RebootInstance = channel.unary_unary(
        '/instance.InstanceService/RebootInstance',
        request_serializer=instance__pb2.RebootInstanceRequest.SerializeToString,
        response_deserializer=instance__pb2.RebootInstanceResponse.FromString,
        )


class InstanceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetInstances(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFlavors(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetImages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateInstance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartInstance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopInstance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteInstance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RebootInstance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InstanceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetInstances': grpc.unary_unary_rpc_method_handler(
          servicer.GetInstances,
          request_deserializer=instance__pb2.GetInstancesRequest.FromString,
          response_serializer=instance__pb2.GetInstancesResponse.SerializeToString,
      ),
      'GetFlavors': grpc.unary_unary_rpc_method_handler(
          servicer.GetFlavors,
          request_deserializer=instance__pb2.GetFlavorsRequest.FromString,
          response_serializer=instance__pb2.GetFlavorsResponse.SerializeToString,
      ),
      'GetImages': grpc.unary_unary_rpc_method_handler(
          servicer.GetImages,
          request_deserializer=instance__pb2.GetImagesRequest.FromString,
          response_serializer=instance__pb2.GetImagesResponse.SerializeToString,
      ),
      'CreateInstance': grpc.unary_unary_rpc_method_handler(
          servicer.CreateInstance,
          request_deserializer=instance__pb2.CreateInstanceRequest.FromString,
          response_serializer=instance__pb2.CreateInstanceResponse.SerializeToString,
      ),
      'StartInstance': grpc.unary_unary_rpc_method_handler(
          servicer.StartInstance,
          request_deserializer=instance__pb2.StartInstanceRequest.FromString,
          response_serializer=instance__pb2.StartInstanceResponse.SerializeToString,
      ),
      'StopInstance': grpc.unary_unary_rpc_method_handler(
          servicer.StopInstance,
          request_deserializer=instance__pb2.StopInstanceRequest.FromString,
          response_serializer=instance__pb2.StopInstanceResponse.SerializeToString,
      ),
      'DeleteInstance': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteInstance,
          request_deserializer=instance__pb2.DeleteInstanceRequest.FromString,
          response_serializer=instance__pb2.DeleteInstanceResponse.SerializeToString,
      ),
      'RebootInstance': grpc.unary_unary_rpc_method_handler(
          servicer.RebootInstance,
          request_deserializer=instance__pb2.RebootInstanceRequest.FromString,
          response_serializer=instance__pb2.RebootInstanceResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'instance.InstanceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
