# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import volume_pb2 as volume__pb2


class VolumeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetVolumes = channel.unary_unary(
        '/volume.VolumeService/GetVolumes',
        request_serializer=volume__pb2.GetVolumesRequest.SerializeToString,
        response_deserializer=volume__pb2.GetVolumesResponse.FromString,
        )


class VolumeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetVolumes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VolumeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetVolumes': grpc.unary_unary_rpc_method_handler(
          servicer.GetVolumes,
          request_deserializer=volume__pb2.GetVolumesRequest.FromString,
          response_serializer=volume__pb2.GetVolumesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'volume.VolumeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
