name: frontend build and deploy 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./sources/frontend
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: install using npm ci 
        run: npm ci
        working-directory: ${{ env.working-directory }}
      - name: build
        run: npm run build
        working-directory: ${{ env.working-directory }}
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./sources/frontend/build
          force_orphan: true
